services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
  
  web:
    build: .
    # 最初はシンプルなコマンドにする
    command: bash -c "bundle install && rails server -b 0.0.0.0"
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp  # ← ここを修正！
      - bundle_data:/usr/local/bundle:cached
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db
    working_dir: /myapp  # 作業ディレクトリを明示

volumes:
  mysql_data:
  bundle_data: